import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import localFont from "next/font/local";

const iranYekan = localFont({
  src: [
    {
      path: "../fonts/IRANYekanX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/IRANYekanX-Black.woff2",
      weight: "900",
      style: "normal",
    },
    // Optional: Only include these if you specifically needed
    // {
    //   path: "../fonts/IRANYekanX-ExtraBlack.woff2",
    //   weight: "950",
    //   style: "normal",
    // },
    // {
    //   path: "../fonts/IRANYekanX-Heavy.woff2",
    //   weight: "1000", // CSS technically supports this, but browser support varies
    //   style: "normal",
    // },
  ],
  variable: "--font-yekan",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${iranYekan.variable} font-sans antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
